###不支持参数后注释，须另起一行
###不允许选项和值之间存在多余的空格

# <默认mpv|ffmpeg> 缩略图引擎的后端
backend=mpv
# 后端的自定义路径。特殊值 default 使用系统 PATH 中的 mpv/ffmpeg
# mpv后端还支持特殊值 bundle （表示MacOS使用bundle-app）
binpath=default
# [mpv后端] Socket 路径，留空即自动
socket=
# 缩略图缓存路径，留空即自动
tnpath=

# 缩略图的最大尺寸，以像素为单位，默认 320
max_height=320
max_width=320
# 不知道用途就别改它
overlay_id=42

# 文件加载后立即启动后端进程（不等待交互触发），默认 no
spawn_first=no
# [mpv后端] 是否退出超时未活动的后端进程（秒），默认 0 即禁用
quit_after_inactivity=0
# 是否对流媒体启用，默认 no
network=no
# 是否对音频文件启用，默认 no
audio=no
# [mpv后端][仅Windows且LuaJIT] 使用WinAPI写入pipe。默认 yes
direct_io=yes

# 使用的解码API（缩略图使用的编码模式中，仅有限api可用且可能强制执行copy），默认 yes 表示优先硬解
hwdec=yes
# 软解线程数（当无法硬解或hwdec为no时生效；超过8无意义），默认 2
sw_threads=2

# 是否只对时长高于该值的视频启用（秒），默认 10 ，值 0 表示禁用
min_duration=10
# <默认0|1|2> 预览精度。0 为自动（仅光标静止时为精确帧），1 为始终关键帧，2 为始终精确帧
precise=0
# [mpv后端] <默认1|2|3> 预览质量模式。1 速度最快但hdr画面略欠饱和， 2 贴近gpu渲染但hdr画面略过饱和， 3 支持了单层杜比正确输出但此时速度很慢
quality=1
# 解码频率（秒），默认 0.125
frequency=0.125
# [ffmpeg后端] <always|默认auto|never> 缓存模式。分别表示 文件加载后预填充；请求时按需缓存；禁用
cache_iframe=auto
# [ffmpeg后端] 内存缓存的最大帧数，默认 128
cache_max=128
# [ffmpeg后端] 缓存 always 模式下的并行后端进程数
be_workers=3
